[package]
name = "usnet_devices"
version = "0.1.0"
authors = ["Kai Lüke <kailueke@riseup.net>"]
license = "MIT"

[dependencies]
netmap_sys = { version = "0.1.4", features = ["netmap_with_libs"], optional = true }
smoltcp = "0.7"
libc = "*"

[features]
default = []
netmap = ["netmap_sys"]
